#!/bin/bash

# Install script for clapp
install() {
  local repo=$(find $HOME -type d -name clapp)
  cp $repo/clapp $HOME/bin || return
  cp -r $repo/.clapp $HOME || return
  # echo -e "\e[0;1;36m[CLApp]\e[0;0;0m CLApp installed!"
}

install