#!/bin/bash

# Install script for clapp
install() {
  local repo=$(find $HOME -type d -name clapp)
  cp $repo/clapp $HOME/bin || return
  cp $repo/.clapp/.lib $HOME/.clapp || return
  cp $repo/.clapp/help $HOME/.clapp || return
  cp $repo/.clapp/version $HOME/.clapp || return
  cp -r $repo/.clapp/assets $HOME/.clapp || return
  cp -r $repo/.clapp/docs $HOME/.clapp || return
}

install