#!/bin/bash

## CLApp Auto Completions ##

_clapp_completions() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local prev="${COMP_WORDS[COMP_CWORD-1]}"
  local RULES="autoup type"
  local CONFIGOPTS="list RESET"
  local ARGS="-t -n -l -o -C -? -h -v -V --type --name --location --options --config --verbose --reset-cfg --help --version --update --docs"
  local TYPES="bash python node javascript sh py js"
  local OPTIONS="src repo"

  # if [[ "$cur" == -* ]]; then
  #   COMPREPLY=( $(compgen -W "$ARGS" -- "$cur") )
  #   return 0
  # fi
  
  case "${prev}" in
    clapp )
      COMPREPLY=( $(compgen -W "$ARGS" -- "$cur") )
      return 0;;
    -t | --type )
      COMPREPLY=( $(compgen -W "$TYPES" -- "$cur") )
      return 0;;
    -l | --location )
      COMPREPLY=( $(compgen -W "$(ls -a | grep '/')" -- "$cur") )
      return 0;;
    -o | --options )
      COMPREPLY=( $(compgen -W "$OPTIONS" -- "$cur") )
      return 0;;
    -C | --config )
      COMPREPLY=( $(compgen -W "$CONFIGOPTS $RULES" -- "$cur") )
      return 0;;
    * )
      COMPREPLY=( $(compgen -W "$ARGS" -- "$cur") )
      return 0;;
  esac
}

complete -F _clapp_completions clapp