#!/usr/bin/env bash

## CLApp Auto Completions ##

_clapp_completions() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local prev="${COMP_WORDS[COMP_CWORD-1]}"
  local RULES="autoup type"
  local CONFIGOPTS="list RESET"
  local ARGS="-t -n -l -o -C -? -h -v -V --type --name --location --options --config --verbose --reset-cfg --help --version --update --docs"
  local TYPES="bash python node javascript sh py js"
  local OPTIONS="src= repo="
  local BASHOPTIONS="altargfunc= commands= states= allone="
  local PYOPTS="venv="
  local JSOPTS="venv= utils= style="
  local FOUNDTYPE
  
  case "${prev}" in
    clapp )
      COMPREPLY=( $(compgen -W "$ARGS" -- "$cur") )
      return 0;;
    -t | --type )
      COMPREPLY=( $(compgen -W "$TYPES" -- "$cur") )
      return 0;;
    -l | --location )
      COMPREPLY=( $(compgen -W "$(ls -a | grep '/')" -- "$cur") )
      return 0;;
    -o | --options )
      # Search for a given type in the command string
      for word in "${COMP_WORDS[@]}"; do
        if [[ "$word" =~ 'sh' ]]; then
          FOUNDTYPE=true
          COMPREPLY=( $(compgen -W "$BASHOPTIONS" -- "$cur") )
          break
        elif [[ "$word" == 'js' || "$word" == 'node' || "$word" == 'javascript' ]]; then
          FOUNDTYPE=true
          COMPREPLY=( $(compgen -W "$JSOPTS" -- "$cur") )
          break
        elif [[ "$word" =~ 'py' ]]; then
          FOUNDTYPE=true
          COMPREPLY=( $(compgen -W "$PYOPTS" -- "$cur") )
          break
        fi
      done
      if [[ -z "$FOUNDTYPE" ]]; then
        COMPREPLY=( $(compgen -W "$OPTIONS" -- "$cur") )
      fi
      return 0;;
    -C | --config )
      COMPREPLY=( $(compgen -W "$CONFIGOPTS $RULES" -- "$cur") )
      return 0;;
    * )
      COMPREPLY=( $(compgen -W "$ARGS" -- "$cur") )
      return 0;;
  esac

  # if [[ "$cur" == 'style=' ]]; then
  #   COMPREPLY=( $(compgen -W "M S P s" -- "$cur") )
  #   return 0
  # fi
  # if [[ "$cur" =~ '^style=.' ]]; then
  #   COMPREPLY=( $(compgen -W "E" -- "$cur") )
  #   return 0
  # fi
  # if [[ "$cur" =~ '^style=..' ]]; then
  #   COMPREPLY=( $(compgen -W "R A E J H" -- "$cur") )
  #   return 0
  # fi
}

complete -F _clapp_completions clapp